---
build_from:
  aarch64: ghcr.io/hassio-addons/debian-base:latest
  amd64: ghcr.io/hassio-addons/debian-base:latest
  armhf: ghcr.io/hassio-addons/debian-base:latest
  armv7: ghcr.io/hassio-addons/debian-base:latest
  i386: ghcr.io/hassio-addons/debian-base:latest
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: CUPS Print Server"
  org.opencontainers.image.description: "CUPS print server for Home Assistant"
  org.opencontainers.image.vendor: "Community"
  org.opencontainers.image.licenses: "MIT"
  org.opencontainers.image.source: "https://github.com/TillitschScHocK/Cupy4HA"
  org.opencontainers.image.documentation: "https://github.com/TillitschScHocK/Cupy4HA"
